### ISSUE TITLE
device-api-usb\lib\prebuilds\win32-x64\node.napi.node is not a valid Win32 application.

### ISSUE THREAD

**Issue by epostsyed** [Huddly/device-api-usb#271]
Node Path in VS
C:\Program Files\nodejs\node.exe
node version 12.20.1

**package.json**
{
  "name": "nodejs-console-app2",
  "version": "0.0.0",
  "description": "NodejsConsoleApp2",
  "main": "app.js",
  "author": {
    "name": ""
  },
  "dependencies": {
    "@huddly/device-api-usb": "^0.2.15",
    "@huddly/sdk": "^0.5.1"
  }
}

**app.js**
'use strict';

const HuddlyDeviceAPIUSB = require('@huddly/device-api-usb').default;
const HuddlySdk = require('@huddly/sdk').default;

**ERROR when running in Windows 10 command**

C:\Users\admin\source\repos\NodejsConsoleApp2\NodejsConsoleApp2>node app.js
internal/modules/cjs/loader.js:1057
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^

Error: \\?\C:\Users\admin\source\repos\NodejsConsoleApp2\NodejsConsoleApp2\node_modules\@huddly\device-api-usb\lib\prebuilds\win32-x64\node.napi.node is not a valid Win32 application.
\\?\C:\Users\admin\source\repos\NodejsConsoleApp2\NodejsConsoleApp2\node_modules\@huddly\device-api-usb\lib\prebuilds\win32-x64\node.napi.node
←[90m    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1057:18)←[39m
←[90m    at Module.load (internal/modules/cjs/loader.js:863:32)←[39m
←[90m    at Function.Module._load (internal/modules/cjs/loader.js:708:14)←[39m
←[90m    at Module.require (internal/modules/cjs/loader.js:887:19)←[39m
←[90m    at require (internal/modules/cjs/helpers.js:74:18)←[39m
    at load (C:\Users\admin\source\repos\NodejsConsoleApp2\NodejsConsoleApp2\node_modules\←[4mnode-gyp-build←[24m\index.js:21:10)
    at Object.<anonymous> (C:\Users\admin\source\repos\NodejsConsoleApp2\NodejsConsoleApp2\node_modules\←[4m@huddly←[24m\device-api-usb\lib\src\bulkusbdevice.js:19:42)
←[90m    at Module._compile (internal/modules/cjs/loader.js:999:30)←[39m
←[90m    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)←[39m
←[90m    at Module.load (internal/modules/cjs/loader.js:863:32)←[39m

**Comment by Remsboys** [comment]
I had the same problem, but with the latest version 0.2.16 it has been resolved.

**Comment by jontore** [comment]
Yes, thank you for reporting this. There was a missing binary, it should be fixed for 0.2.15 as well.
